### ISSUE TITLE
可以弄成一个网页吗？

### ISSUE THREAD

**Issue by liaosimin** [idoubi/sql2struct#8]
我觉得可以弄成一个网页，点开这个网页就能用。不需要按照插件。
不需要部署到服务器里。把整个网页所需文件打包进一个文件夹就行。

**Comment by idoubi** [comment]
可以的。找时间弄一下

**Comment by alswl** [comment]
@liaosimin try this https://t.log4d.com/sql2struct/html/sql2struct.html .

**Comment by idoubi** [comment]
新版网页版：https://dou.tools/sql2struct/
